src/S3Commands.cc, src/S3Commands.hh
There were actually two issues that broke authenticated buckets. The first was that we weren't properly setting the host header. The second was that we weren't generating a valid canonical URI that gets signed and sent as a part of the Authorization header. The solution to both of these was to parse the hostUrl more carefully, and in only one spot.
Testing this is a bit of a challenging setup, so I'll try to loosely sketch this out here. This is from my notes, and it assumes you're running in a linux container as root. The container will need all the tools for building c++, as well as xrootd and the minio server binary. You'll also need a non-root user to run the xrootd process under. I'm also assuming you have some experience dealing with XRootD and all its funkiness.
```
Download & …
```
=> Fix issue with host header and canonicalURI

src/S3Commands.cc
The range header was malformed, causing objects that didn't fit in a single buffer to fail on GET.
=> Fix OB1 error

src/S3Commands.cc, src/S3Commands.hh, src/S3File.cc, src/S3File.hh, src/S3FileSystem.cc, src/S3FileSystem.hh
This takes PR #16 and adds the "window dressing" laid out in issue #10
Closes #10
=> Add path-style hosting to plugin

CMakeLists.txt, src/AWSCredential.hh, src/AWSv4-impl.cc, src/AWSv4-impl.hh, src/HTTPCommands.cc, src/HTTPCommands.hh, src/HTTPDirectory.hh, src/HTTPFile.cc, src/HTTPFile.hh, src/HTTPFileSystem.cc, src/HTTPFileSystem.hh, src/S3Commands.cc, src/S3Commands.hh, src/S3Directory.hh, src/S3File.cc, src/S3File.hh, src/S3FileSystem.cc, src/S3FileSystem.hh, src/logging.cc, src/logging.hh, src/shortfile.cc, src/shortfile.hh, src/stl_string_utils.cc
Includes:
- Adding copyright notices to each source file.
- Use XRootD's logging framework and corresponding configuration.
- Re-arrange/cleanup headers
- Fix all compilation warnings identified by Mac OS X's compiler.
=> Simple cleanups of the S3/HTTP backend code

src/HTTPFile.cc, src/HTTPFileSystem.cc, src/HTTPFileSystem.hh
Built on top of #21; merge that first.
=> Add support for more generic HTTP prefixes

CMakeLists.txt, README.md, src/S3AccessInfo.cc, src/S3AccessInfo.hh, src/S3Commands.cc, src/S3Commands.hh, src/S3File.cc, src/S3File.hh, src/S3FileSystem.cc, src/S3FileSystem.hh
These changes allow a single xrootd to talk to multiple secure buckets in S3.
=> S3 Multibucket

CMakeLists.txt, src/HTTPCommands.cc, src/HTTPCommands.hh, src/HTTPFile.cc, src/HTTPFile.hh, src/HTTPFileSystem.cc, src/HTTPFileSystem.hh, src/S3Commands.hh, src/S3File.cc, src/TokenFile.cc, src/TokenFile.hh, test/CMakeLists.txt, test/http_tests.cc
(Note: given the extensive infrastructure improvements in #35, I built this PR on top of #35.  Don't try to review this until after #35 is merged)
This PR adds support for adding a bearer token to requests made by the HTTPFileSystem OSS plugin.  When configured, all requests will be made with the token read from the configured file.
The file is reloaded every 5 seconds, meaning that a short-lived token can be used if the file is updated.
=> Token support for HTTP backend

src/S3Commands.cc, test/s3_tests.cc
The service URL could technically contain a resource.  E.g.,
```
https://foo.example.com/prefix
```
or simply
```
https://foo.example.com/
```
In this case, the code logic didn't handle bucket names correctly, generating invalid URLs for directory listings and stat's.
This fixes said logic and adds some simple regression test coverage.
Fixes issues with NCAR S3 origin not being able to perform HEAD requests.
=> Correctly handle the case with trailing slash in the service URL

src/S3Commands.cc, src/S3Commands.hh, src/S3File.cc, src/S3File.hh
uploads to s3 using multipart uploads. Testing seems to be working, b…
=> uploads to s3 using multipart uploads. 

.github/workflows/test.yml, CMakeLists.txt, src/CurlUtil.cc, src/CurlUtil.hh, src/CurlWorker.hh, src/HTTPCommands.cc, src/HTTPCommands.hh, src/HTTPFile.cc, src/HTTPFileSystem.cc, src/S3Commands.cc, src/S3Commands.hh, src/S3File.cc, src/S3FileSystem.cc, src/logging.cc, src/logging.hh, test/CMakeLists.txt, test/http_tests.cc, test/s3-setup.sh, test/s3-stress-test.sh, test/s3-teardown.sh, test/s3-test.sh, test/s3_tests.cc, test/xrdhttp-setup.sh, test/xrdhttp-teardown.sh, test/xrdhttp-test.sh
We've noticed the performance of the plugin is horribly slow -- to the point where we don't have enough cores in machines to have the origin keep up with the caches (why the caches are pushing so hard is a separate story).
A few judicious uses of `pstack` indicates that almost all the CPU time is spent in TLS handshakes.  It turns out that the `curl_easy_*` APIs have no connection reuse unless you reuse the handle itself.  So, _every single request_ is a separate TLS connection to the upstream HTTP / S3 server.  That is indeed, no fun.
This takes motivation (and code) from https://github.com/PelicanPlatform/xrdcl-pelican to have all the requests handled in a set of separate worker threads.  The request object enters a queue, is processed by a worker, and then, on completion, the original …
=> Switch curl to using the multi-handle & workers

CMakeLists.txt
Do not overwrite the original values of CMAKE_SHARED_LINKER_FLAGS and CMAKE_MODULE_LINKER_FLAGS. The original values contain the content of the LDFLAGS environment variable. If these variables are overwritten instead of extended, the content of LDFLAGS will be ignored.
Use the module name when calling find_package, not the target name defined in the module.
=> Fix some cmake glitches

CMakeLists.txt
```
undefined reference to `XrdOssDF::pgRead(void*, long, unsigned int, unsigned int*, unsigned long long)'
undefined reference to `XrdOssDF::pgWrite(void*, long, unsigned int, unsigned int*, unsigned long long)'
```
Xrootd is compiled using -D_FILE_OFFSET_BITS=64. This means that the second parameter in pgRead/pgWrite, which is declared as off_t in xrootd's headers, is a long long on 32 bit architectures. Without -D_FILE_OFFSET_BITS=64 the off_t is a long and there is a mismatch which leads to a linking error.
Add -D_FILE_OFFSET_BITS=64 to the compiler definitions so that the compilation uses the same off_t definition as xrootd does during compilation.
=> Fix linking error on 32 bit architectures

test/s3_unit_tests.cc
In particular, this includes a (commented out for now) reproducer for the issue described in #63.  That test can be re-enabled when the bug is fixed (or used to test the fix itself!).
=> Add unit tests covering the `list` and `stat` functionality

CMakeLists.txt, src/CurlUtil.cc, src/HTTPCommands.cc, src/HTTPCommands.hh, src/HTTPFile.cc, src/S3Commands.cc, src/S3Commands.hh, src/S3File.cc, src/S3File.hh, test/s3_unit_tests.cc
This PR introduces buffered reads -- reads go through a new cache layer, including prefetch.
This is built on top of the streaming reads patch and should be merged after that one.
=> Buffered Reads

test/s3_unit_tests.cc
```
/builddir/build/BUILD/xrootd-s3-http-0.1.8-build/xrootd-s3-http-0.1.8/test/s3_unit_tests.cc: In member function ‘virtual void AmazonS3SendMultipartPartLowercase::modifyResponse(std::string&)’:
/builddir/build/BUILD/xrootd-s3-http-0.1.8-build/xrootd-s3-http-0.1.8/test/s3_unit_tests.cc:589:22: error: ‘transform’ is not a member of ‘std’
589 |                 std::transform(resp.begin(), resp.end(), resp.begin(),
|                      ^~~~~~~~~
gmake[2]: *** [test/CMakeFiles/s3-unit-test.dir/build.make:82: test/CMakeFiles/s3-unit-test.dir/s3_unit_tests.cc.o] Error 1
gmake[2]: Leaving directory '/builddir/build/BUILD/xrootd-s3-http-0.1.8-build/xrootd-s3-http-0.1.8/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:359: test/CMakeFiles/s3-unit-test.dir/all] Error 2
gmake[1]: *** …
```
=> Include <algorithm> for std::transform

CMakeLists.txt
Do not override the value given using -DCMAKE_BUILD_TYPE
=> Do not hardcode the build type

CMakeLists.txt, cmake/FindAtomic.cmake
On some 32-bit platforms, explicit linking against libatomic is required for atomics to be utilized.  Test that at the CMake level, adding an import target as we did for `std::filesystem` that can be used.
Based on the suggestion from:
https://github.com/PelicanPlatform/xrootd-s3-http/pull/81
=> Check if we need to link against libatomic

.github/workflows/test.yml, CMakeLists.txt, src/CurlUtil.cc, src/CurlUtil.hh, src/S3Commands.cc, test/CMakeLists.txt, test/s3-gowrk-test.sh, test/s3-setup.sh, test/xrdhttp-setup.sh
With the small fixes in this PR, the stress test can now be run under ASAN without triggering any crash.
=> Add stress test (and small fixes)

src/S3File.cc, src/S3File.hh, test/s3-setup.sh
This fixes two issues found so far while stress testing:
1.  A crash that occurs if the file is closed while reads were pending.
2. A deadlock that occurs if the state mutex is held while files are going into queue.
I can no longer get the plugin to crash under Pelican downloads of the test data.  However, it still periodically "stalls out" -- not returning any data from AWS -- so there's still something to hunt down.
=> Fix deadlocks and crashes

rpm/xrootd-s3-http.spec
We want a buildable RPM for use in the upstream Pelican Dockerfile -- here's an attempt for a future 0.2.1.
=> Fix RPM-based builds

test/xrdhttp-setup.sh
When the network is disabled connecting to the hostname returned by the hostname command is not always possible.
=> Use the hostname localhost for http tests

test/s3-setup.sh, test/xrdhttp-setup.sh
10 seconds is not always sufficient.
Here is a test run on ricci.debian.org, the Debian riscv64 porter box with an increased timeout:
```
22: xrootd daemon PID: 4157210
22: XRootD logs are available at /.../xrootd-s3-http-0.2.1/obj-riscv64-linux-gnu/tests/basic/server.log
22: Waiting for xrootd to start (2 seconds so far) ...
22: Waiting for xrootd to start (3 seconds so far) ...
22: Waiting for xrootd to start (4 seconds so far) ...
[ ... ]
22: Waiting for xrootd to start (25 seconds so far) ...
22: Waiting for xrootd to start (26 seconds so far) ...
22: Waiting for xrootd to start (27 seconds so far) ...
22: xrootd started at https://ricci:39891/
```
The test log and the server log from the test are attached.
[testlog.txt](https://github.com/user-attachments/files/18634186/testlog.txt) …
=> Increase the timeout when waiting for the xrootd server to start

CMakeLists.txt, src/Filter.cc, src/Filter.hh, test/CMakeLists.txt, test/filter_tests.cc, test/s3-setup.sh, test/s3-test.sh
This PR (note: it's built on top of #79 and hence it contains those commits -- ignore them for review purposes or wait until that PR is merged) adds a new module, `libXrdOssFilter`, for managing what objects are exported via XRootD.
`libXrdOssFilter` can be stacked on top of the HTTP or S3 OSS plugin and provides reasonably fine-grained control over what data is accessible.  The administrator can limit things to specific prefixes or only objects matching a certain glob (e.g., `/ncar/dataset*/**` or `/foo/*.png`).  It supports the "globstar" operator, allowing multiple path hierarchies to be matched (e.g., `/pelican/**/*.go` will export all `*.go` files underneath `/pelican`).  The integration test contains a valid XRootD configuration file demonstrating this.
Includes reasonable unit test …
=> Module for filtering exports

src/CurlUtil.cc, src/S3Commands.cc, src/S3Commands.hh, src/S3File.cc, src/S3File.hh, src/logging.cc
In particular, at the `debug` level this will record the success of reads; at `warning`, this will record the read's failure reason.
=> Add some verbose logging messages

CMakeLists.txt, rpm/xrootd-s3-http.spec
Use `XrdOss` as the prefix for any OSS plugin (e.g., `XrdOssS3` or `XrdOssHttp`).  Update the RPM spec as well.
=> Rename plugins to match upstream's preferences

.github/workflows/test.yml, CMakeLists.txt, README.md, rpm/xrootd-s3-http.spec, src/AWSCredential.hh, src/Posc.cc, src/Posc.hh, src/S3File.cc, src/S3File.hh, test/CMakeLists.txt, test/http_tests.cc, test/lsan-suppressions.txt, test/posc_tests.cc, test/s3-setup.sh, test/s3_unit_tests.cc, test/xrdhttp-setup.sh
This plugin makes it so any files being uploaded are not visible in the namespace until they have been successfully closed by the client.  Files that are partially uploaded by the client -- or were being uploaded when the server crashed -- will eventually be deleted.
This would prevent files from being accidentally read & cached prior to being completed.
=> Create a "Persist on Successful Close" plugin

src/S3File.cc
Adds a missing guard for an offset value for m_b.off.
A regression test for this cannot be created because the specific circumstances and load under which this occurs is almost impossible to create artificially.
This should close #113
=> Added missing check for next_offset < m_parent.content_length
